/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminProfileView: typeof import('./src/modules/admin/views/AdminProfileView.vue')['default']
    AgendaAdmin: typeof import('./src/modules/admin/components/AgendaAdmin.vue')['default']
    AgendaMedico: typeof import('./src/modules/medico/components/AgendaMedico.vue')['default']
    AgendaPaciente: typeof import('./src/modules/paciente/components/AgendaPaciente.vue')['default']
    AuthLayout: typeof import('./src/layouts/AuthLayout.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Chip: typeof import('primevue/chip')['default']
    ConfigAdmin: typeof import('./src/modules/admin/components/ConfigAdmin.vue')['default']
    ConfigMedico: typeof import('./src/modules/medico/components/ConfigMedico.vue')['default']
    ConfigPaciente: typeof import('./src/modules/paciente/components/ConfigPaciente.vue')['default']
    DefaultLayout: typeof import('./src/layouts/DefaultLayout.vue')['default']
    DemoExample: typeof import('./src/modules/videocall/components/DemoExample.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginForm: typeof import('./src/modules/auth/components/LoginForm.vue')['default']
    LoginView: typeof import('./src/modules/auth/views/LoginView.vue')['default']
    MedicosForm: typeof import('./src/modules/auth/components/MedicosForm.vue')['default']
    MedicosProfileView: typeof import('./src/modules/medico/views/MedicosProfileView.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    MenuProfile: typeof import('./src/components/MenuProfile.vue')['default']
    PacienteProfileView: typeof import('./src/modules/paciente/views/PacienteProfileView.vue')['default']
    PacientesForm: typeof import('./src/modules/auth/components/PacientesForm.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    ProfileAdmin: typeof import('./src/modules/admin/components/ProfileAdmin.vue')['default']
    ProfileLayout: typeof import('./src/layouts/ProfileLayout.vue')['default']
    ProfileMainLayout: typeof import('./src/layouts/ProfileMainLayout.vue')['default']
    ProfileMedico: typeof import('./src/modules/medico/components/ProfileMedico.vue')['default']
    ProfilePaciente: typeof import('./src/modules/paciente/components/ProfilePaciente.vue')['default']
    RegisterView: typeof import('./src/modules/auth/views/RegisterView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionLanding: typeof import('./src/components/SectionLanding.vue')['default']
    SelectMenuProfile: typeof import('./src/layouts/SelectMenuProfile.vue')['default']
    TabMenu: typeof import('primevue/tabmenu')['default']
    Tag: typeof import('primevue/tag')['default']
    Timeline: typeof import('primevue/timeline')['default']
    VideoCallView: typeof import('./src/modules/videocall/views/VideoCallView.vue')['default']
    VideoWebRTC: typeof import('./src/modules/videocall/components/VideoWebRTC.vue')['default']
    VideoWebRTCSetup: typeof import('./src/modules/videocall/components/VideoWebRTCSetup.vue')['default']
  }
}
